version: '3'
services:
  admin:
    env_file:
      - .env
    environment:
      - HOST=${ADMIN_HOST}
      - PORT=${ADMIN_PORT}
    build: ./admin
    hostname: ${ADMIN_HOST}
    ports:
      - ${ADMIN_PUB_PORT}:${ADMIN_PORT}
    links:
      - data-gen:${DATA_GEN_HOST}
      - postgres:${DB_HOST}
    depends_on:
      - postgres

  admin-db-gen:
    env_file:
      - .env
    build: ./admin
    command: db.py
    depends_on:
      - postgres
    links:
      - postgres:${DB_HOST}

  admin-tasks:
    env_file:
      - .env
    build: ./admin
    entrypoint: celery -A tasks worker -l debug --no-color
    depends_on:
      - highcharts
      - postgres
      - redis
      - rabbit
    links:
      - highcharts:${HIGHCHARTS_HOST}
      - postgres:${DB_HOST}
      - rabbit:${RABBIT_HOST}
      - redis:${REDIS_HOST}

  data-gen:
    env_file:
      - .env
    environment:
      - HOST=${DATA_GEN_HOST}
      - PORT=${DATA_GEN_PORT}
    build: ./data-gen
    hostname: ${DATA_GEN_HOST}
    links:
    - postgres:${DB_HOST}
    depends_on:
      - postgres

  highcharts:
    image: onsdigital/highcharts-export-node
    entrypoint: highcharts-export-server --enableServer 1 --port ${HIGHCHARTS_PORT}

  postgres:
    image: postgres:9.6
    volumes:
      - dashboard-data:/var/lib/postgresql/data

  redis:
    image: redis:4
    volumes:
      - tasks-result-data:/data
    command: redis-server --appendonly yes --port ${REDIS_PORT}

  rabbit:
    image: rabbitmq:3.7
    volumes:
      - tasks-data:/var/lib/rabbitmq

volumes:
  dashboard-data:
  tasks-data:
  tasks-result-data:
